### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by gkv91** [kenshohara/video-classification-3d-cnn-pytorch#15]
Hi,
After some iteration of the code (around 500 videos), it stops by saying the following.
**out of memory at /opt/conda/condabld/pytorch_1523244252089/work/torch/lib/THC/generic/THCStorage.cu:58..**
But I still have free memory on my GPU. What will be the issue?. How can I run it on one GPU instead of multiple GPU?

Thanks

**Comment by adamcasson** [comment]
I'm getting the following error on certain videos

`RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58`

Running on a 1080 Ti

**Comment by kenshohara** [comment]
If you have a sufficient memory of GPUs to use the model,
I'm not sure about it.
If you do not have a sufficient memory, please try more shallow model.

**Comment by gkv91** [comment]
Hi @adamcasson , I solved the memory error by reducing the batch size. Thanks :)

**Comment by adamcasson** [comment]
@gkv91 wow great tip, works perfectly with my GPU now, thanks!
@kenshohara shallow model works well too. Great repo and research, thanks!

**Comment by winnechan** [comment]
it is weird that there was a problem of "cuda runtime error (77) : an illegal memory access was encountered" when the video of 300 frames but not video of 100 frames, someone can help? i am new to pytorch [awk]
